### ISSUE TITLE
Unable to link account

### ISSUE THREAD

**Issue by bruidbarrett** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#10]
**Describe the bug**
Unable to link account error for attempting to link any account to youplanets account

All accounts and devices, mobile or desktop
Win 10 64bit

**Screenshots**
![Capture](https://user-images.githubusercontent.com/15036078/101999939-a96a2980-3c96-11eb-95e2-27904a281fd8.PNG)

**Comment by Seraph-YCZhang** [comment]
Can you try with the full link, e.g https://www.instagram.com/username/

**Comment by bruidbarrett** [comment]
It doesn’t let me insert a link at all

**Comment by Seraph-YCZhang** [comment]
@JalenYes I think we need a placeholder or autofocus on the input field when clicking edit, what  do you think

**Comment by JalenYes** [comment]
> @JalenYes I think we need a placeholder or autofocus on the input field when clicking edit, what do you think

I totally agree with you. What we have is the same as the UI/UX design. Apparently, many people don't know how to edit it. I'll inform Diana to update a version of the design for that. Now, I'll just put a placeholder.

**Comment by JalenYes** [comment]
> It doesn’t let me insert a link at all
> […](#)

It's the UI misleading you. You need to click the edit pen to make it editable first. It's the design trying to make it unique and clean.

**Comment by JalenYes** [comment]
> > It doesn’t let me insert a link at all
> > […](#)
> 
> It's the UI misleading you. You need to click the edit pen to make it editable first. It's the design trying to make it unique and clean.

Please let us know if you successfully link your accounts! We will certainly make the experience not confusing at all in the next version. Thank you!

**Comment by JalenYes** [comment]
Moved social links to the planet setting page. UI is not optimized yet.
