### ISSUE TITLE
Video player works well on Safari but not on Chrome

### ISSUE THREAD

**Issue by JalenYes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#100]
**Describe the bug**
Video player works well on Safari but not on Chrome. 

**Screenshots**
<img width="394" alt="image" src="https://user-images.githubusercontent.com/40333215/108029362-4a5cc400-6ffb-11eb-8482-ca4de692d715.png">

<img width="477" alt="image" src="https://user-images.githubusercontent.com/40333215/108029494-84c66100-6ffb-11eb-868f-f31ac0bc976a.png">

**Reproduce**
Check the video on youplanets.com Space.

**Comment by Seraph-YCZhang** [comment]
![image](https://user-images.githubusercontent.com/20440998/108085134-ffff3580-7042-11eb-964b-82041d398c01.png)
I will check what type of video is supported

**Comment by JalenYes** [comment]
I see. there is not a lot we can do.  Is there a way that we can detect if the video is playable or not? if not playable, we set it like what Circle does. 

<img width="711" alt="image" src="https://user-images.githubusercontent.com/40333215/108106556-1b2a6f00-705c-11eb-803c-c02bef6efa19.png">

**Comment by Seraph-YCZhang** [comment]
> I see. there is not a lot we can do. Is there a way that we can detect if the video is playable or not? if not playable, we set it like what Circle does.
> 
> <img alt="image" width="711" src="https://user-images.githubusercontent.com/40333215/108106556-1b2a6f00-705c-11eb-803c-c02bef6efa19.png">

Can you provide more information, is this the same video uploaded to space? if not can it be played on our site? It is hard to check that because the container type of the video is correct, but the way it encoded is not supported

**Comment by JalenYes** [comment]
The video is here. It is .MOV. but it is able to play on our app. 
https://user-images.githubusercontent.com/40333215/108113961-2da9a600-7066-11eb-9bc6-7f619334a2c0.MOV

**Comment by Seraph-YCZhang** [comment]
Yes not all .mov unsupported as I said, some of them are okay, but some are not okay, that's the tough point, so can I make a guess circle doesn't show all the .mov files?

**Comment by JalenYes** [comment]
> Yes not all .mov unsupported as I said, some of them are okay, but some are not okay, that's the tough point, so can I make a guess circle doesn't show all the .mov files?

I think so. may be we can do the same for .MOV. that video shows on mobile chrome but not desktop chrome.

**Comment by Seraph-YCZhang** [comment]
> > Yes not all .mov unsupported as I said, some of them are okay, but some are not okay, that's the tough point, so can I make a guess circle doesn't show all the .mov files?
> 
> I think so. may be we can do the same for .MOV.
> 
> BTW, that video shows on mobile chrome but not desktop chrome.

if you want, we can do that

**Comment by JalenYes** [comment]
> > > Yes not all .mov unsupported as I said, some of them are okay, but some are not okay, that's the tough point, so can I make a guess circle doesn't show all the .mov files?
> > 
> > 
> > I think so. may be we can do the same for .MOV.
> > BTW, that video shows on mobile chrome but not desktop chrome.
> 
> if you want, we can do that

Let me call Diana. update to you soon

**Comment by JalenYes** [comment]
Diana is going to test it on Pinterest, Patreon, and Ins to see how they handle it. Will update it to us later

**Comment by JalenYes** [comment]
Issue fixed. Users are able to upload .mov file but the file is on downloading style. 
<img width="965" alt="image" src="https://user-images.githubusercontent.com/40333215/108300435-4d2bf600-716e-11eb-9183-3f4b303e43e8.png">
