### ISSUE TITLE
Collect number doesn't increase

### ISSUE THREAD

**Issue by JalenYes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#101]
**Describe the bug**
Account A click collect -> collect + 1 
Account B still see 0 collect no matter how many people have collected it.

**Screenshots**
<img width="896" alt="image" src="https://user-images.githubusercontent.com/40333215/108106939-968c2080-705c-11eb-83ac-34d2cef6c1b1.png">

**Comment by Seraph-YCZhang** [comment]
No, we don't record that

**Comment by JalenYes** [comment]
Oh, I think we need to record it. because number of collect is also an important metric to show how good a post is. As post on Space is growing over time, we will need to have a sort of recommendation system. what do you think? 

BTW, I also found that for visitor (no account signed in) to check comment, it shows a 0. like pic below. 
<img width="881" alt="Screen Shot 2021-02-16 at 2 14 53 PM" src="https://user-images.githubusercontent.com/40333215/108110745-b6721300-7061-11eb-91be-2e305bd1318a.png">

**Comment by Seraph-YCZhang** [comment]
Most websites don't show it, because it is some privacy-related I guess

**Comment by JalenYes** [comment]
> Most websites don't show it, because it is some privacy-related I guess

You mean showing number of collects for a post?

**Comment by Seraph-YCZhang** [comment]
Yes. And for the number of comments, what's the issue in the photo?

**Comment by JalenYes** [comment]
> Yes. And for the number of comments, what's the issue in the photo?

yea, we don't show who collected the post. However, we need to show the number of collects for a post. Currently, the number of collect does not grow even though 10 people have collected the post.  It seems like only working on local, which means you can see which one you collected. it never goes to 2 collects.

**Comment by Seraph-YCZhang** [comment]
> > Yes. And for the number of comments, what's the issue in the photo?
> 
> yea, we don't show who collected the post. However, we need to show the number of collects for a post. Currently, the number of collect does not grow even though 10 people have collected the post. It seems like only working on local, which means you can see which one you collected. it never goes to 2 collects.

So what websites showing the number

**Comment by JalenYes** [comment]
Not a lot apps in US have it. But a lot of apps in China have it. The original reason we want to have it is that we want to cultivate collect culture, just like RED app because the post on Space is posted by Planeter. So the post itself is supposed to be high-quality and helpful. 

It actually doesn't matter either having it or not.  If doesn't have it, we need to remove the number instead of having the number counting locally.

**Comment by Seraph-YCZhang** [comment]
> Not a lot apps in US have it. But a lot of apps in China have it. The original reason we want to have it is that we want to cultivate collect culture, just like RED app because the post on Space is posted by Planeter. So the post itself is supposed to be high-quality and helpful.
> 
> It actually doesn't matter either having it or not. If doesn't have it, we need to remove the number instead of having the number counting locally.
