### ISSUE TITLE
UI issues on mobile

### ISSUE THREAD

**Issue by JalenYes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#102]
**Describe the bug**
Pic 1: title and planet info are overlapped. Maybe we can cut the title if it is beyond certain words on mobile OR move the planet info a little bit down on mobile. 
Pic 2: we need to make the card view 1 column like pic 3.

**Screenshots**
pic 1:
![IMG_2084](https://user-images.githubusercontent.com/40333215/108114524-e839a880-7066-11eb-9e52-ca7a8c6513d4.PNG)
pic 2:
![IMG_2085](https://user-images.githubusercontent.com/40333215/108114527-ea036c00-7066-11eb-8dcb-8a3ab8a9e669.PNG)
pic 3:
![IMG_2086](https://user-images.githubusercontent.com/40333215/108114893-66964a80-7067-11eb-9601-fd890d5293f7.PNG)

**Comment by Seraph-YCZhang** [comment]
I remember you have made the 1 col layout, did we change that?

**Comment by JalenYes** [comment]
No. I did not change it. Your code is the latest code

________________________________

**Comment by JalenYes** [comment]
issue fixed!
