### ISSUE TITLE
Bio: null issue

### ISSUE THREAD

**Issue by JalenYes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#105]
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/40333215/108611976-1e9e5d00-73b2-11eb-8abc-fe89d1ef1ecb.png">

**Comment by Seraph-YCZhang** [comment]
I have fixed the null. One more question is should the display name be displayed in all the places? Because for now, when I make a comment, it still shows my username.

**Comment by JalenYes** [comment]
Thank you for backing it up!  🖖 

Yes, for display name and user name, we just need to make it same as Twitter and IG. Username is the social handle (like @jjalen_fu). Display name is being displayed all the places (like Jalen Fu).

**Comment by JalenYes** [comment]
fixed by Yuchen.
