### ISSUE TITLE
Error With Payment Formatting

### ISSUE THREAD

**Issue by bruidbarrett** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#11]
**Describe the bug**
When random junk is inserted for payment info the error is outputted above price, also formatting is incorrect 

**Screenshots**
![2](https://user-images.githubusercontent.com/15036078/102000087-4aa5af80-3c98-11eb-99f8-d56bbbd8ddc6.PNG)

**To Reproduce**
type literally anything incorrect into payment sections

**Comment by JalenYes** [comment]
Payment experience could be 10X optimized, like adding [trending animation](https://medium.com/bridge-collection/improve-the-payment-experience-with-animations-3d1b0a9b810e) and loading animation.

**Comment by JalenYes** [comment]
The issue of error output has been solved! UI Formatting will be fixed in the next version on Monday. Thank you!
