### ISSUE TITLE
Visitor experience for Ask Anything & Schedule a Call

### ISSUE THREAD

**Issue by JalenYes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#12]
**Describe the solution you'd like**
Three kinds of user experience for Visitors (need Designer and Engineer to discuss which one is the ideal way): 
1. Require Visitors to signup in the first place. When Ask Now/Schedule Now is clicked, triggering the SignIn component under the AuthModals folder. No redirect. Just keep users in the Ask Anything/Schedule a call page. 
2. Only require Visitors to signup in the last step of the asking and scheduling process. 
3. No signup needed for Visitors to schedule a call or ask request. The email and name in the asking and scheduling process will be the unique identifier.

**Comment by AdvaithNair** [comment]
If you enter your email and name (3rd approach), and leave the website, how will you view your question's status? Moreover, what if that email is already taken by a user? I would assume to view the question's answer, you'd have to make an account with that email, which makes things a lot more complicated, especially from a backend perspective. At some point, the user will have to create an account to be able to actually use YouPlanets, so I'd recommend something like the 2nd approach (which I believe has been in the design for a while but I haven't got around to implementing it for Ask Anything). Let me know your thoughts though.
