### ISSUE TITLE
Inconsistent in new user's profile pics

### ISSUE THREAD

**Issue by Seraph-YCZhang** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#13]
**Describe the bug**
These two profile pics are not consistent 

**Screenshots**
![image](https://user-images.githubusercontent.com/20440998/102031215-4904e600-3d83-11eb-9a94-ff713e7da4e7.png)

**To Reproduce**
create a new account without a profile pic and post something

I think we should put this default profile on the backend instead of the frontend

**Comment by JalenYes** [comment]
Good catch! We not only need to make it consistent but also need to have a better default profile pic. The current one is just a bootstrap version.

**Comment by JalenYes** [comment]
Fixed
