### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by Seraph-YCZhang** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#15]
**Describe the bug**
if you scroll down, you cannot get the search content and my screen is blocked

**Screenshots**
![image](https://user-images.githubusercontent.com/20440998/102156461-9c426b80-3e4b-11eb-893d-e605c9c9dd64.png)

Possible solution:
Use client X and Y to control the position of dropdown

**Comment by JalenYes** [comment]
Thank you so much for the report! I'm aware of this issue for a long time. I'll try to make it smooth ASAP.

**Comment by Seraph-YCZhang** [comment]
Make it fixed solving the problem, do you want me to commit it

**Comment by JalenYes** [comment]
> Make it fixed solving the problem, do you want me to commit it

wow, that's amazing! pls commit it into your current PR. Thank you so much!
