### ISSUE TITLE
 unknown days in ask question metrics

### ISSUE THREAD

**Issue by Seraph-YCZhang** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#19]
**Describe the bug**
 unknown days, I don't know if this unknown is intentional?

**Screenshots**
![image](https://user-images.githubusercontent.com/20440998/102700419-2d825b00-421b-11eb-844c-9985663486cd.png)

**To Reproduce**
local env, planet name Youxiu => ask anything

**Comment by JalenYes** [comment]
This has been fixed.
