### ISSUE TITLE
Two issues with Ask Anything

### ISSUE THREAD

**Issue by JalenYes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#24]
**Describe the bug**
1. Add Card button and Editing Icon disappeared. I guess it might be something wrong with cleaning the codebase last week. 
2. Ask Now button should be disabled to Planeter him/herself. 

**Screenshots**
 I'm the Planeter of the planet in the screenshot below.
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/40333215/103237075-943aff00-4914-11eb-8c5f-1483123dfe3e.png">

**Comment by JalenYes** [comment]
@AdvaithNair  If this issue has been solved in your branch, please pull request to qa-branch ASAP. This bug has been shown on production for days.

**Comment by AdvaithNair** [comment]
Whoops, I thought I submitted the PR a while back but I'll do it right now. It should be fixed now.

**Comment by JalenYes** [comment]
Issue resolved! Hope next time, we all check emails more frequently.
