### ISSUE TITLE
Attempted to Set Gender

### ISSUE THREAD

**Issue by AdvaithNair** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#25]
**Describe the bug**
When I tried to select the Male gender, I was prompted with "null" as the value.

**Screenshots**
![Issue](https://user-images.githubusercontent.com/41276902/103350229-23026580-4a54-11eb-8898-7cd23dce379c.jpg)

**To Reproduce**
1. Create new user.
2. Go to [https://www.youplanets.com/youPlanets/user/account](https://www.youplanets.com/youPlanets/user/account) (automatically redirected here after user creation).
3. Click on edit icon for Gender input.
4. Select Male gender.

Other Notes:
I had to select Female (showed "female"), then Other (showed "other"), then Prefer not to say (showed "Prefer not to say", which is correct). Then clicked Male again (showed "male"). There seems to be an issue with lowercase as well.

**Desktop (please complete the following information):**
 - OS: macOS X Catalina
 - Browser: Chrome

**Comment by JalenYes** [comment]
This is fixed!
