### ISSUE TITLE
Cannot choose Male as a gender during sign-up

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#31]
This is for new users (not just creators). When you sign up, "Male" is selected by default as a gender, but when you save, it still remains "null". Instead, you have to select a different gender, then go back to "Male", then it will work. But it's not intuitive. 

Also, can we show blank "" (nothing) instead of null?

**Comment by JalenYes** [comment]
Issue has been fixed!
