### ISSUE TITLE
#Topics added, but did not show when posted

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#33]
![image](https://user-images.githubusercontent.com/77167655/104048816-805f8a80-51a9-11eb-98c1-33f849bfeda6.png)

**Comment by Seraph-YCZhang** [comment]
@JalenYes Hi Jalen, what's the designed logic flow of this, create and click to add the topic as two steps, or create and attach the topic to this post as one step?

**Comment by JalenYes** [comment]
> @JalenYes Hi Jalen, what's the designed logic flow of this, create and click to add the topic as two steps, or create and attach the topic to this post as one step?

This is not your fault. The UI design didn't show it at that time. Intuitively, usually the time you create the hashtag is the time you want to use it as a creator.  Don't need to make any changes for now. I'll let Diana make a decision.

**Comment by JalenYes** [comment]
We will switch topic in community to topic in each channel. Creator will set available topic in channel setting page instead of the posing box. So this issue will be automatically fixed in the new user flow.
