### ISSUE TITLE
Cannot edit post once posted

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#35]
![image](https://user-images.githubusercontent.com/77167655/104049083-efd57a00-51a9-11eb-8bca-fb1049331a7c.png)

I can only delete but cannot edit to add pictures / updates / etc...

**Comment by JalenYes** [comment]
By current design, we do not allow users to edit a post once it has been posted. This follows twitter.  I know Reddit, Slack, and Discord all allow users to edit it. In my opinion, I think either not editable or showing 'edited' word if it has been edited. But I would like to know more opinion on that.

**Comment by JalenYes** [comment]
Post editing and comment editing/deleting functions are released.
