### ISSUE TITLE
Important: Unable to Remove Credit Card once Added

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#36]
This is important because it makes users/creators scared when they cannot remove their cards

![image](https://user-images.githubusercontent.com/77167655/104049580-cff28600-51aa-11eb-8625-032306eb8826.png)

Also there is no place in their Account where creators/users can see their payment methods and edit them (Add more card, remove, or change)

**Comment by Seraph-YCZhang** [comment]
Sorry for that, it is actually removed, but not updated on the page, will be fixed in the next PR

**Comment by JalenYes** [comment]
Issue fixed! Thanks so much for the reporting!
