### ISSUE TITLE
Link of Space: myspace/space could run into copyright/trademark issue with MySpace

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#38]
![image](https://user-images.githubusercontent.com/77167655/104250525-61742900-5433-11eb-9006-0b6f04a57171.png)

Not a bug per se, but we should change the link naming convention and how we refer to "My Space". My Space is a trademarked name and we can't use theirs.

**Comment by hansontranhai** [comment]
Maybe "My Universe" ? :D

**Comment by JalenYes** [comment]
> Maybe "My Universe" ? :D

Good point! Never thought about it before. When we build this feature, we have three names to choose: Space, Galaxy, For You.

**Comment by JalenYes** [comment]
issue solved.
