### ISSUE TITLE
Search functionality for topics not working

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#39]
Both for the My Collection page and the My Planet page:
![image](https://user-images.githubusercontent.com/77167655/104255116-ee23e480-543d-11eb-852d-19ea2579e542.png)

![image](https://user-images.githubusercontent.com/77167655/104255031-c2086380-543d-11eb-8f48-7b7c920197d0.png)

**Comment by Seraph-YCZhang** [comment]
@JalenYes Search in planet seems will be removed in the design? Search in the collection will be fixed in the next PR.

**Comment by JalenYes** [comment]
There is no search topics in community because we will make topic itself clickable. Search in collection has been fixed.
