### ISSUE TITLE
Text in intro video and planet info should align left

### ISSUE THREAD

**Issue by DianaDai-meh** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#42]
<img width="626" alt="Screen Shot 2021-01-13 at 1 19 01 AM" src="https://user-images.githubusercontent.com/75862075/104414007-7b9a2e00-553d-11eb-83d5-1967b4453123.png">

<img width="581" alt="Screen Shot 2021-01-13 at 1 22 16 AM" src="https://user-images.githubusercontent.com/75862075/104414171-c7e56e00-553d-11eb-819d-f0d7dee606cf.png">

**Comment by JalenYes** [comment]
It is aligned left now. Issue fixed!
