### ISSUE TITLE
Color change in drop down

### ISSUE THREAD

**Issue by DianaDai-meh** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#45]
**Describe the bug**
Hover color should change together on following planet and my planet

**Screenshots**
<img width="308" alt="Screen Shot 2021-01-13 at 1 59 24 AM" src="https://user-images.githubusercontent.com/75862075/104417257-134e4b00-5543-11eb-9b3d-f394bdbeeb37.png">

**Comment by JalenYes** [comment]
This has been fixed in staging PR. Once the PR got merged, you will see the change on youplanets.com
