### ISSUE TITLE
Incorrect button name

### ISSUE THREAD

**Issue by DianaDai-meh** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#46]
**Describe the bug**
button name incorrect, and please change it to outline button style, not primary button style

**Screenshots**
user- my notification
<img width="313" alt="Screen Shot 2021-01-13 at 2 01 22 AM" src="https://user-images.githubusercontent.com/75862075/104417502-7809a580-5543-11eb-99af-ed9707eea6f8.png">

planeter- planet notification
<img width="330" alt="Screen Shot 2021-01-13 at 2 01 33 AM" src="https://user-images.githubusercontent.com/75862075/104417514-7cce5980-5543-11eb-8b89-6cc915557562.png">

**Comment by JalenYes** [comment]
This has been fixed in stagging PR. 
![image](https://user-images.githubusercontent.com/40333215/104417614-b1daac00-5543-11eb-9b0b-fe7b18a44ef3.png)
![image](https://user-images.githubusercontent.com/40333215/104417624-b4d59c80-5543-11eb-9cfd-b1409b17eebb.png)
