### ISSUE TITLE
Add a switcher button for planters

### ISSUE THREAD

**Issue by DianaDai-meh** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#47]
**Describe the bug**
Please add a switcher button for planters, design is in Planter Setting on sketch cloud

**Screenshots**
<img width="265" alt="Screen Shot 2021-01-13 at 2 04 58 AM" src="https://user-images.githubusercontent.com/75862075/104417681-c5861280-5543-11eb-8b9c-6363146e6aa3.png">

**Comment by JalenYes** [comment]
I'll add the switcher and icons. You will see it on youplanets.com very soon
