### ISSUE TITLE
Add a default collection name

### ISSUE THREAD

**Issue by DianaDai-meh** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#48]
**Describe the bug**
Could we add a default collection name in the editor box, like my loves/my likes

**Screenshots**
<img width="640" alt="Screen Shot 2021-01-13 at 2 09 30 AM" src="https://user-images.githubusercontent.com/75862075/104418096-696fbe00-5544-11eb-9465-2ded3d1ab6c1.png">

**Comment by JalenYes** [comment]
issue fixed: The default collection name is called: default.
