### ISSUE TITLE
User experience enhancement 

### ISSUE THREAD

**Issue by DianaDai-meh** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#49]
**Describe the bug**
Please see detailed design for collect function in **Space-collect** in Sketch cloud

<img width="336" alt="Screen Shot 2021-01-13 at 2 16 21 AM" src="https://user-images.githubusercontent.com/75862075/104418707-57424f80-5545-11eb-93b1-769b6b69979d.png">

**Comment by JalenYes** [comment]
Is there still some UI difference between youplanets.com V1.1 and high-fi design? @DianaDai-meh   Please test it on youplanets.com V1.1

**Comment by JalenYes** [comment]
Request update: change the input element to a select element to show all the options of created collection names. 'Default' as default option if there is no more collections other than the 'default' one. 
<img width="994" alt="image" src="https://user-images.githubusercontent.com/40333215/105659543-f5fc7380-5e96-11eb-849e-70df6cf5f173.png">

**Comment by Seraph-YCZhang** [comment]
> Request update: change the input element to a select element to show all the options of created collection names. 'Default' as default option if there is no more collections other than the 'default' one.
> <img alt="image" width="994" src="https://user-images.githubusercontent.com/40333215/105659543-f5fc7380-5e96-11eb-849e-70df6cf5f173.png">

There is a list showing all the options if you have multiple options

**Comment by JalenYes** [comment]
for some reasons, the list does not cover all of my collection names. pic 1 shows my collections. pic 2 shows the list when I collect. 
![image](https://user-images.githubusercontent.com/40333215/105807195-8c9e6280-5f73-11eb-9fa6-ff33f3f930be.png)

![image](https://user-images.githubusercontent.com/40333215/105807229-9758f780-5f73-11eb-8d96-a2c6b81452dd.png)

**Comment by Seraph-YCZhang** [comment]
> for some reasons, the list does not cover all of my collection names. pic 1 shows my collections. pic 2 shows the list when I collect.
> ![image](https://user-images.githubusercontent.com/40333215/105807195-8c9e6280-5f73-11eb-9fa6-ff33f3f930be.png)
> 
> ![image](https://user-images.githubusercontent.com/40333215/105807229-9758f780-5f73-11eb-8d96-a2c6b81452dd.png)

The current behavior is based on autocomplete, which means abc doesn't match default, if you type in a or ab you will see abc, or if input is empty you can see more

**Comment by JalenYes** [comment]
I just found it. Thank you! It makes sense. I'll close this issue.
