### ISSUE TITLE
Post can be collected twice in beta & unknown grey lines

### ISSUE THREAD

**Issue by DianaDai-meh** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#51]
**Describe the bug**

 

- [ ] Found this problem in beta, and seems like  youplanets.com do not have this issue
- [ ] why there are grey lines around collection?

**Screenshots**

<img width="972" alt="Screen Shot 2021-01-13 at 2 22 19 AM" src="https://user-images.githubusercontent.com/75862075/104419319-4e05b280-5546-11eb-9ec6-544beaf98e42.png">

**Comment by JalenYes** [comment]
A duplicated issue with #52.
