### ISSUE TITLE
Mobile: Missing homepage link in the mobile version

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#53]
This is the homepage when first visited youplanets.com:

![image](https://user-images.githubusercontent.com/77167655/104469980-c4bea200-557e-11eb-87eb-8ae23e04e252.png)

When you navigate away, the homepage disappears, and you cannot get back to it. Instead, it shows this:

![image](https://user-images.githubusercontent.com/77167655/104470085-e7e95180-557e-11eb-99ac-5ca907f0ff06.png)

I'm using Iphone IOS 12

**Comment by JalenYes** [comment]
Currently, homepage is /home/following page. No typical page to introduce features.
