### ISSUE TITLE
My Questions doesn't show any Past Questions even though the planet already has 2 questions

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#54]
![image](https://user-images.githubusercontent.com/77167655/104470334-37c81880-557f-11eb-8858-0c3db8b75bf6.png)
![image](https://user-images.githubusercontent.com/77167655/104470376-44e50780-557f-11eb-9ca7-0ad6e892dc65.png)

**Comment by JalenYes** [comment]
Seems like you should check Planet Question in Planet Studio. The naming does confuse sometimes.

**Comment by hansontranhai** [comment]
Oh I see now. Maybe change "My Questions" for "Users" to "Questions I asked" 
My Questions can mean questions given to me to answer, so a planeteer would think that's where they go to see the questions fans asked them to answer.

**Comment by hansontranhai** [comment]
I would also bring Planet Studio up in the menu for planeteers. They would use that a lot more than "Users"

**Comment by JalenYes** [comment]
> I would also bring Planet Studio up in the menu for planeteers. They would use that a lot more than "Users"

Planet studio is in the account dropdown menu, under for planeter section

**Comment by JalenYes** [comment]
> Oh I see now. Maybe change "My Questions" for "Users" to "Questions I asked" 
> 
> My Questions can mean questions given to me to answer, so a planeteer would think that's where they go to see the questions fans asked them to answer.

Will do.
