### ISSUE TITLE
My Notifications not showing history / new comments/likes

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#55]
![image](https://user-images.githubusercontent.com/77167655/104483167-6ea52b00-558d-11eb-8bbe-c8fcc397debf.png)

**Comment by hansontranhai** [comment]
This can be closed because I went to the wrong place. I see it in Planet Notifications now.

**Comment by JalenYes** [comment]
> This can be closed because I went to the wrong place. I see it in Planet Notifications now.

I'll keep the issue opened until I found a design to clear the confusion
