### ISSUE TITLE
Comment Submission / Edit or Delete after submission?

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#56]
After I submitted the comment, it should clear the comment box instead of leaving the same comment there, because then I'm confused whether the comment got submitted or whether I have to submit again.

Then if I end up submitting a duplicate comment, how do I edit or delete it? 

![image](https://user-images.githubusercontent.com/77167655/104483560-e07d7480-558d-11eb-9ce7-2929179b56fa.png)

**Comment by JalenYes** [comment]
Thanks for opening the issue! This will be fixed soon.

**Comment by JalenYes** [comment]
Issue Updates: Comment box currently is cleared when the comment is posted. Edit and Delete functionality will be added soon.

**Comment by JalenYes** [comment]
I'll close this issue. Will add edit / delete functionality for comments together with for post in my next PR.
