### ISSUE TITLE
Explore button on landing page

### ISSUE THREAD

**Issue by Seraph-YCZhang** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#6]
**Describe the bug**
The button is covered by the menu

**Screenshots**
![image](https://user-images.githubusercontent.com/20440998/101957842-38f8d500-3bd0-11eb-9d0e-b345cc20ee12.png)

**To Reproduce**

**Smartphone (please complete the following information):**

**Comment by JalenYes** [comment]
Thank you for the report! This bug is fixed. Feel free to let me know if you have any other questions. Thank you!
