### ISSUE TITLE
SIGN UP button too small - not visible on HomePage

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#60]
First, it's not available on the homepage. So you already have to find it, which hinders new user enrollment. 
Then, once you click on "Sign In", the sign up button is all the way down below, in small font. I missed it a couple times. 

Sign-up option should be front and center, and very easy to see, because that's how we obtain new clients and new users.

![image](https://user-images.githubusercontent.com/77167655/104500404-03b31e80-55a4-11eb-82fd-f4c511e170c2.png)

![image](https://user-images.githubusercontent.com/77167655/104500442-10377700-55a4-11eb-84f3-a601cf0ca714.png)

**Comment by DianaDai-meh** [comment]
Change Don't have an account to (16, regular), Sign up here (16, semi bold, #6275BF)

**Comment by JalenYes** [comment]
Issue fixed in V1.1.1 release!
