### ISSUE TITLE
Consistent Pricing for Members v. Non Members, with Clear Explanations and Distinctions

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#61]
Need to have the pricing consistent, with clear explanation/distinction if there are different treatments of members versus non-members. Otherwise, creators and fans will be very confused. plus, if all it takes to avoid paying $5 is to sign up - that can encourage a lot of people to sign up (so they can ask for free). But if we don't state that out loud, people will pay and then regret it cause they didn't know better.

**Comment by JalenYes** [comment]
Issue fixed. 

Lite Planet: 
Public Q&A -> No discount to members.
Private Q&A -> No discount to members.

Pro Planet:
Public Q&A -> Members are able to ask public Q&A for free.
Private Q&A -> No discount to members.
