### ISSUE TITLE
Progress bar (Ask Anything)

### ISSUE THREAD

**Issue by JalenYes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#66]
**Describe the bug**
Progress doesn't go to confirm when users complete the question. 

**Screenshots**
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/40333215/104521781-91eecb00-55cb-11eb-8f4b-c2497b4a6c6a.png">

**Comment by AdvaithNair** [comment]
This issue has been fixed, I'll PR the solution

**Comment by JalenYes** [comment]
Issue solved!
