### ISSUE TITLE
Become a Member for $0 / month - Too scary

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#67]
I would really take out the **"for $0 a month"**. Usually, signing up on social media sites is free - that's the standard. If we say "$0/month" - the implication is that at some point in the future, it will go up. And while that might be true, we should let creators deal with their fanbase and set their own subscription for their planet. If I were new and saw this, I wouldn't sign up.

![image](https://user-images.githubusercontent.com/77167655/104619081-16d0f780-5653-11eb-9a03-86f8fe8cf0b3.png)

**Comment by JalenYes** [comment]
@Seraph-YCZhang  I'll let you know what need to be changed soon

**Comment by JalenYes** [comment]
We changed the text to be Join now for free if the price is 0, which is lite plan. Users still need to go through check out process. I would like to know more user feedback about it.
