### ISSUE TITLE
change blue underline to w 72, h 4, radius 2

### ISSUE THREAD

**Issue by DianaDai-meh** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#69]
change blue underline to w 72, h 4, radius 2, also apply to tabs in planets

<img width="501" alt="Screen Shot 2021-01-14 at 2 25 10 PM" src="https://user-images.githubusercontent.com/75862075/104638746-8e634e80-5674-11eb-9a90-b4d0d344ea2b.png">

**Comment by JalenYes** [comment]
height and radius have been changed successfully. however the width of the underline depends on the width of the tab text. For example, if the text is longer, the width is longer. 
<img width="443" alt="image" src="https://user-images.githubusercontent.com/40333215/104639755-c74ff300-5675-11eb-94f9-a93888196cc7.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/40333215/104639771-cb7c1080-5675-11eb-9028-198bfa7d39d0.png">
