### ISSUE TITLE
Signup is covered in Signin modal in space

### ISSUE THREAD

**Issue by Seraph-YCZhang** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#7]
**Describe the bug**
Sign up is not clickable

**Screenshots**

![image](https://user-images.githubusercontent.com/20440998/101958051-93923100-3bd0-11eb-9502-5e8f0d1e45be.png)

**Smartphone (please complete the following information):**
 - Device: iPhone6s
 - Browser: safari

**Comment by JalenYes** [comment]
Thank you for the report! This has been fixed! Feel free to let me know if there are still some problems with that.
