### ISSUE TITLE
Can we make the "Likes" and "Comments" pictures bigger?

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#71]
Creators care a lot about how popular a post is. Right now, it just looks too tiny compared to the post

![image](https://user-images.githubusercontent.com/77167655/104661430-1d309500-568e-11eb-9ada-77f22b4ea93f.png)

**Comment by JalenYes** [comment]
fixed. 
<img width="282" alt="image" src="https://user-images.githubusercontent.com/40333215/105453684-8e53e780-5c4e-11eb-850c-4a0accfe5667.png">
