### ISSUE TITLE
Give Creators ability to sync YouPlanets calendars with their own calendars or create a reminder on their phone

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#73]
To minimize no-show and fan's frustration. Helps creators keep their ratings up.

![image](https://user-images.githubusercontent.com/77167655/104662795-2a02b800-5691-11eb-9496-a6e387a8dc0e.png)

**Comment by JalenYes** [comment]
1. We do have no-show protection system. I'll explain to you a little bit later. 
2. The schedules did sync to the calendar you connected, either Google Calendar or Office 365. We currently only have in-app notification and email notification about the status of the call schedule. No text notification system. We don't have a plan to build it for now.  For the reminder, your calendar provider will remind you 15 mins before the scheduled time. YouPlanets will in-app remind you 30 mins before the scheduled time. 

I'll schedule a call with you on your planet. Please test and feel the whole experience, and tell us every single step of the experience (including withdraw payout process) and which functionality we need to enhance.

**Comment by JalenYes** [comment]
I just added Scheduling Assistant email notification to fans and creators on beta. Your calendar provider will notify you 15 mins before the call. Schedule Assistant will notify you via email 30 mins before the call.
