### ISSUE TITLE
Unable to save changes

### ISSUE THREAD

**Issue by DianaDai-meh** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#75]
**Describe the bug**
<img width="775" alt="Screen Shot 2021-01-14 at 10 44 57 PM" src="https://user-images.githubusercontent.com/75862075/104678798-40713980-56ba-11eb-871b-35442726e908.png">

<img width="939" alt="Screen Shot 2021-01-14 at 10 44 06 PM" src="https://user-images.githubusercontent.com/75862075/104678808-4535ed80-56ba-11eb-83c9-d9730e036077.png">

<img width="1213" alt="Screen Shot 2021-01-14 at 10 48 38 PM" src="https://user-images.githubusercontent.com/75862075/104678995-a9f14800-56ba-11eb-88cf-912cc26acda4.png">

**Comment by JalenYes** [comment]
Make sure you logged in. and try again.  

If you got it this time, it's the problem of log in system.

**Comment by JalenYes** [comment]
Please check if you got this already.

**Comment by JalenYes** [comment]
Issue closed! There shouldn't be any problems about Save Changes.
