### ISSUE TITLE
Schedule time in view detail page doesn't match the real schedule time 

### ISSUE THREAD

**Issue by JalenYes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#76]
**Describe the bug**
Schedule time in view detail page doesn't match the real schedule time. Pic 1 shows the schedule time in detail page. Pic 2 shows the real scheduled time. 

**Screenshots**
<img width="923" alt="image" src="https://user-images.githubusercontent.com/40333215/104792099-4c690400-576b-11eb-9a4c-eecce57696f3.png">
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/40333215/104792107-50952180-576b-11eb-894f-e774fc1a961d.png">

**Comment by Seraph-YCZhang** [comment]
@JalenYes Which one do you prefer

**Comment by JalenYes** [comment]
I don’t mean the style of time display. I mean one is Jan 15 and the another one is Jan 18 which is the right time scheduled.

________________________________

**Comment by Seraph-YCZhang** [comment]
okay, I will fix this

**Comment by JalenYes** [comment]
Issue fixed! Thanks Yuchen!
