### ISSUE TITLE
Email notification for Schedule a Call

### ISSUE THREAD

**Issue by JalenYes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#78]
**Describe the bug**
1. Email notification layout 
2. Confirm/Reschedule/Cancel links in Schedule Assistant email doesn't work (pic 1). It links to 404 page.
![image](https://user-images.githubusercontent.com/40333215/105806546-2fee7800-5f72-11eb-81ae-b46dc516e0a4.png)

**Comment by Seraph-YCZhang** [comment]
what is the Email notification layout about?

**Comment by JalenYes** [comment]
> what is the Email notification layout about?

It's awesome that you look into this and try to solve the problem. It's good to have you back up in the engineering part.  

The goal here is at least replacing the Nylas email notification with our own brand and design (currently doesn't have interface design, so we can just slightly copy Nylas one). you can open Chrome and Safari to try to go though every status of the schedule both sides. 
<img width="1763" alt="image" src="https://user-images.githubusercontent.com/40333215/107593832-60731a80-6bde-11eb-926c-591530db94e4.png">

**Comment by JalenYes** [comment]
> > what is the Email notification layout about?
> 
> It's awesome that you look into this and try to solve the problem. It's good to have you back up in the engineering part.
> 
> The goal here is at least replacing the Nylas email notification with our own brand and design (currently doesn't have interface design, so we can just slightly copy Nylas one). you can open Chrome and Safari to try to go though every status of the schedule both sides.
> <img alt="image" width="1763" src="https://user-images.githubusercontent.com/40333215/107593832-60731a80-6bde-11eb-926c-591530db94e4.png">

Replacing means three things. 1. email sent from our youplanets notification account. 2. email layout 3. that .ics file to allow the schedule to be on guest's calendar.

**Comment by JalenYes** [comment]
> > > what is the Email notification layout about?
> > 
> > 
> > It's awesome that you look into this and try to solve the problem. It's good to have you back up in the engineering part.
> > The goal here is at least replacing the Nylas email notification with our own brand and design (currently doesn't have interface design, so we can just slightly copy Nylas one). you can open Chrome and Safari to try to go though every status of the schedule both sides.
> > <img alt="image" width="1763" src="https://user-images.githubusercontent.com/40333215/107593832-60731a80-6bde-11eb-926c-591530db94e4.png">
> 
> Replacing means three things. 1. email sent from our youplanets notification account. 2. email layout 3. that .ics file to allow the schedule to be on guest's calendar.

I do not recommend we do it right now. We either do it one time like I just mention OR keep Nylas one but fix the url matching issue.

**Comment by JalenYes** [comment]
Let me know how do you think. And I think you should take a break. You've been working very hard for a long time.

**Comment by JalenYes** [comment]
Perfectly done by Yuchen!
