### ISSUE TITLE
Stop rendering PlanetPage twice + rendering previous state 

### ISSUE THREAD

**Issue by JalenYes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#8]
**Is your feature request related to a problem? Please describe.**
1. Users will feel frustrated that Planet Page renders twice. I don't know if it's a better choice to solve this problem when we integrate Next.js. 
2. When a page is rendered, sometimes users can see the previous state, like image, numbers, and etc. 

**Describe the solution you think might solve the issue**
Next.js?

**Comment by Seraph-YCZhang** [comment]
Hi Jalen, I tried to improve the behavior a little bit, can you try it on my branch to see if you like it?
