### ISSUE TITLE
Schedule a Call feature - takes forever to load, and customizing has some glitch

### ISSUE THREAD

**Issue by hansontranhai** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#80]
![image](https://user-images.githubusercontent.com/77167655/105377018-f9aaa480-5bcf-11eb-980c-fa01d65f8c2f.png)

**Comment by JalenYes** [comment]
I’ll look into it.

**Comment by JalenYes** [comment]
I'm able to get the schedule now. 
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/40333215/105446576-68274b00-5c40-11eb-866d-ed57fcaf272a.png">

**Comment by JalenYes** [comment]
I found out it's the problem of Nylas (third-party calendar API provider). They encounter some kind of technical incident early today. I did get status notification from them. It already got fixed now.
