### ISSUE TITLE
A bug on Updates from planeters 

### ISSUE THREAD

**Issue by JalenYes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#86]
**Describe the bug**
not sorting the posts and showing purple circle when something new from the planeter .  pic 1 shows all of updates. pic 2 after clicking Hanson profile picture, it is supposed to show the posts from creator Hanson. However, it shows nothing. pic 3 same on creator YouPlanets. 

**Screenshots**
pic 1: ![image](https://user-images.githubusercontent.com/40333215/106197290-84ffd900-6180-11eb-9a87-b4167276e63f.png)

pic 2: ![image](https://user-images.githubusercontent.com/40333215/106197576-e627ac80-6180-11eb-8b4b-1956abe95715.png)

pic 3: 
![image](https://user-images.githubusercontent.com/40333215/106197626-f2ac0500-6180-11eb-928d-ab50f6869c1b.png)

**Comment by Seraph-YCZhang** [comment]
I don't know about this component

**Comment by JalenYes** [comment]
Okay, no worries. I'll solve it later today.

**Comment by Seraph-YCZhang** [comment]
probably fixed plz have a test

**Comment by JalenYes** [comment]
OMG, thank you! I was planing to look into it after reaching out a few of YouTubers. I'll test it right now.
