### ISSUE TITLE
Mobile Scroll Footer Issue

### ISSUE THREAD

**Issue by bruidbarrett** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#9]
When you’re on mobile the footer of the webpage covers the bottom “explore” button no matter how far you try to scroll down
![744FB4A4-AB1B-46E0-AC54-CFB4DD3D861C](https://user-images.githubusercontent.com/15036078/101999864-f00b5400-3c95-11eb-836f-64efa455fdfe.png)

**Comment by JalenYes** [comment]
Hello bruidbarrett, 

Thank you for your report! Can you please let us know the smartphone version? Thank you! We will fix it in the next version release, which will be on Monday next week.

**Comment by JalenYes** [comment]
This is fixed.
