### ISSUE TITLE
Launch Planet Unsuccessfully 

### ISSUE THREAD

**Issue by Nancyyes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#92]
Hi guys,

I am a friend of Jalen, and I am testing Youplanets. My planet cannot be launched even though I have updated my payment as the order. Also, after editing the bio of my planet, there is a big empty. The below is a screenshot of the problems.

Thank you!

Best,
Nancy 
![image](https://user-images.githubusercontent.com/58830422/107451463-52a59280-6b15-11eb-8fcc-98c8afce7885.png)

**Comment by Nancyyes** [comment]
Sorry, the empty is not in the bio. It's in the "About me" part.

**Comment by JalenYes** [comment]
Problem solved! 1. it's because Stripe need to verify her information. There is no notification to her. So she is confused. 2. She needs to upload a YouTube video with link. This is the only way we're supporting.
