### ISSUE TITLE
Upload planet background pic interface

### ISSUE THREAD

**Issue by DianaDai-meh** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#93]
**Describe the bug**
Upload planet background pic interface
**Screenshots**
<img width="1433" alt="Screen Shot 2021-02-09 at 1 33 38 AM" src="https://user-images.githubusercontent.com/75862075/107457905-f5174300-6b20-11eb-953f-1ff5c1d781e4.png">

**Comment by JalenYes** [comment]
this is fixed. will put it into next version

**Comment by JalenYes** [comment]
This is fixed.
