### ISSUE TITLE
In space channel, but can't post to space 

### ISSUE THREAD

**Issue by Nancyyes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#94]
![image](https://user-images.githubusercontent.com/58830422/107464620-b2f4fe00-6b2e-11eb-9287-80b40eee86a9.png)

**Comment by JalenYes** [comment]
@Seraph-YCZhang @AdvaithNair  It's interesting that her posting box in Space channel does not show Post to space.

**Comment by JalenYes** [comment]
Her planet is launched today.

**Comment by Seraph-YCZhang** [comment]
I see there is a space channel id = 42, is_space = false in database

**Comment by JalenYes** [comment]
fixed
