### ISSUE TITLE
Unable to post pic/ video to space and channel

### ISSUE THREAD

**Issue by DianaDai-meh** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#95]

**Comment by JalenYes** [comment]
The issue is fixed.

**Comment by JalenYes** [comment]
Can't upload a pic/video 
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/40333215/107478773-06c01100-6b48-11eb-9ee7-971240a21fe7.png">
<img width="866" alt="image" src="https://user-images.githubusercontent.com/40333215/107478788-0f184c00-6b48-11eb-9286-0ca09fe0305a.png">

**Comment by JalenYes** [comment]
This is fixed by Yuchen.
