### ISSUE TITLE
Bad description 

### ISSUE THREAD

**Issue by DianaDai-meh** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#96]
**Describe the bug**
Please write better description on both

**Screenshots**
<img width="1018" alt="Screen Shot 2021-02-10 at 12 10 14 AM" src="https://user-images.githubusercontent.com/75862075/107467684-90fe7a00-6b34-11eb-9d8d-603babf58e62.png">

**Comment by JalenYes** [comment]
![image](https://user-images.githubusercontent.com/40333215/108003469-e917ff00-6fc0-11eb-8059-dc8b1d4e2891.png)

Is this good?

**Comment by JalenYes** [comment]
Issue fixed!
