### ISSUE TITLE
Create a Topic doesn't work

### ISSUE THREAD

**Issue by JalenYes** [Plaxy-Technologies-Inc/YouPlanets-Bug-Report#98]
**Describe the bug**
No response when clicking Create

**Screenshots**
![image](https://user-images.githubusercontent.com/40333215/107996103-92ed9080-6fad-11eb-92a1-3b43fdf4dbbe.png)

**Desktop (please complete the following information):**

**Comment by Seraph-YCZhang** [comment]
works fine on my beta, I have no way to test it on .com

**Comment by Seraph-YCZhang** [comment]
Works fine on beta, I have no way to test it on .com

**Comment by Seraph-YCZhang** [comment]
if no more detail provided. I will submit the PR for fixing the dayjs issue

**Comment by JalenYes** [comment]
Sorry. I think this bug appears in the channel setting when you're creating a new channel.  Not shown after the channel is created or on existing channels.

**Comment by JalenYes** [comment]
So, basically, if you try to add a topic when you're creating a new channel. Create button doesn't work.

**Comment by Seraph-YCZhang** [comment]
Okay I will remove it because you don't have a channel id when you are creating one

**Comment by JalenYes** [comment]
Topic setting is removed when creating a channel, which isn't the best experience for setting topics for a channel. However, it's not necessary to do more changes on this.
